# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit_test', '0002_auto_20170731_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='guid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
