# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit_test', '0003_rabbit_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='date_upload',
            field=models.DateField(auto_now=True),
        ),
    ]
