# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit_test', '0004_rabbit_date_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='D:\\projects\\rabbittest\\uploads'),
        ),
    ]
